"""add role

Revision ID: 12efdcc9ab0e
Revises: 2f200b72e49f
Create Date: 2026-08-31 18:42:02.066472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12efdcc9ab0e'
down_revision: Union[str, Sequence[str], None] = '2f200b72e49f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role = sa.Enum("member","admin",name="user_role")
    user_role.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', user_role, nullable=True))
    op.execute("UPDATE users SET role = 'member' WHERE role is NULL")
    op.alter_column("users","role",existing_type=user_role,nullable=False,)
    # ### end Alembic commands ###


def downgrade():
    user_role = sa.Enum("member", "admin", name="user_role")

    op.drop_column("users", "role")

    user_role.drop(op.get_bind())