"""add is_active column

Revision ID: af6e7feef257
Revises: 56f2c14f5d44
Create Date: 2026-09-07 17:53:29.228131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6e7feef257'
down_revision: Union[str, Sequence[str], None] = '56f2c14f5d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE authors SET  is_active=True WHERE is_active is NULL")
    op.alter_column("authors","is_active",existing_type=sa.Boolean(),nullable=False)
    op.add_column('books', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE books SET is_active = True WHERE is_active is NULL")
    op.alter_column("books","is_active",existing_type=sa.Boolean(),nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_active =True WHERE is_active is NULL")
    op.alter_column("users","is_active",existing_type=sa.Boolean(),nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('books', 'is_active')
    op.drop_column('authors', 'is_active')
    # ### end Alembic commands ###
